# Generated by Django 2.1.7 on 2020-02-04 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Basic_info', '0001_initial'),
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='po',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_po', to='Order.Po', verbose_name='我公司PoNO'),
        ),
        migrations.AddField(
            model_name='material',
            name='po_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_po_detail', to='Order.Po_detail', verbose_name='po_detail'),
        ),
        migrations.AddField(
            model_name='material',
            name='qc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_qc', to='Basic_info.Staff', verbose_name='QC'),
        ),
        migrations.AddField(
            model_name='material',
            name='qty_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_fac_qty_unit', to='Basic_info.Unit', verbose_name='数量单位'),
        ),
        migrations.AddField(
            model_name='factory',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fac_area', to='Basic_info.Area', verbose_name='所在地区代号'),
        ),
        migrations.AddField(
            model_name='factory',
            name='export_company_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fac_company', to='Basic_info.Export_company', verbose_name='进出口公司代码'),
        ),
        migrations.AddField(
            model_name='factory',
            name='fac_texture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fac_texture', to='Basic_info.Texture', to_field='name', verbose_name='生产材质'),
        ),
        migrations.AddField(
            model_name='factory',
            name='fmr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fmr_staff', to='Basic_info.Staff', verbose_name='评估工厂的FMR人员'),
        ),
        migrations.AddField(
            model_name='customer_mark',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_customer', to='Basic_info.Customer', verbose_name='客户代码'),
        ),
        migrations.AddField(
            model_name='code',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_area', to='Basic_info.Area', verbose_name='所属地区'),
        ),
        migrations.AddField(
            model_name='code',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_dep', to='Basic_info.Department', verbose_name='所属部门'),
        ),
        migrations.AddField(
            model_name='area',
            name='fmr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_fmr', to='Basic_info.Staff', verbose_name='负责的FMR'),
        ),
        migrations.AddField(
            model_name='area',
            name='qc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_qc', to='Basic_info.Staff', verbose_name='负责的QC'),
        ),
    ]
