# Generated by Django 2.1.7 on 2020-02-04 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_info', '0002_auto_20200204_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code_area', to='Basic_info.Area', verbose_name='所属地区'),
        ),
        migrations.AlterField(
            model_name='code',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='code_dep', to='Basic_info.Department', verbose_name='所属部门'),
        ),
        migrations.AlterField(
            model_name='customer_mark',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mark_customer', to='Basic_info.Customer', verbose_name='客户代码'),
        ),
        migrations.AlterField(
            model_name='factory',
            name='export_company_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fac_company', to='Basic_info.Export_company', verbose_name='进出口公司代码'),
        ),
        migrations.AlterField(
            model_name='material',
            name='belong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_category', to='Basic_info.Material_cate', verbose_name='所属材料类别'),
        ),
        migrations.AlterField(
            model_name='material',
            name='po',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_po', to='Order.Po', verbose_name='我公司PoNO'),
        ),
        migrations.AlterField(
            model_name='material',
            name='qty_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_fac_qty_unit', to='Basic_info.Unit', verbose_name='数量单位'),
        ),
        migrations.AlterField(
            model_name='matrial_process',
            name='m_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mat_process_code', to='Basic_info.Texture', verbose_name='材料编码'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_comp', to='Basic_info.Company', verbose_name='所属公司'),
        ),
        migrations.AlterField(
            model_name='texture_process',
            name='texture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='texture_process_texture', to='Basic_info.Texture', verbose_name='材质ID'),
        ),
    ]
