# Generated by Django 2.1.7 on 2020-02-20 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Basic_info', '0003_auto_20200204_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preset1', models.TextField(blank=True, null=True, verbose_name='预留字段1')),
                ('preset2', models.TextField(blank=True, null=True, verbose_name='预留字段2')),
                ('preset3', models.TextField(blank=True, null=True, verbose_name='预留字段3')),
                ('preset4', models.TextField(blank=True, null=True, verbose_name='预留字段4')),
                ('preset5', models.TextField(blank=True, null=True, verbose_name='预留字段5')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '员工上下级信息',
                'verbose_name_plural': '员工上下级信息',
                'db_table': 'employee_relationship',
                'ordering': ['staff'],
            },
        ),
        migrations.AlterField(
            model_name='staff',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_form',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='聘用形式'),
        ),
        migrations.AddField(
            model_name='employeerelationship',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch_staff', to='Basic_info.Staff', verbose_name='直接下属'),
        ),
        migrations.AddField(
            model_name='employeerelationship',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leader_staff', to='Basic_info.Staff', verbose_name='直接上司'),
        ),
        migrations.AddField(
            model_name='employeerelationship',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_name', to='Basic_info.Staff', verbose_name='员工'),
        ),
    ]
