# Generated by Django 2.1.7 on 2020-02-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory', models.CharField(blank=True, max_length=255, null=True, verbose_name='工厂')),
                ('yields', models.CharField(blank=True, max_length=255, null=True, verbose_name='工厂日产量')),
                ('per_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='人均产量')),
                ('person', models.CharField(blank=True, max_length=255, null=True, verbose_name='人数')),
                ('pass_rate', models.CharField(blank=True, max_length=255, null=True, verbose_name='合格率')),
                ('preset1', models.TextField(blank=True, null=True, verbose_name='预留字段1')),
                ('preset2', models.TextField(blank=True, null=True, verbose_name='预留字段2')),
                ('preset3', models.TextField(blank=True, null=True, verbose_name='预留字段3')),
                ('preset4', models.TextField(blank=True, null=True, verbose_name='预留字段4')),
                ('preset5', models.TextField(blank=True, null=True, verbose_name='预留字段5')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '工厂产能',
                'verbose_name_plural': '工厂产能',
                'db_table': 'factory_ability',
                'ordering': ['factory'],
            },
        ),
        migrations.CreateModel(
            name='FactoryProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('things', models.TextField(blank=True, null=True, verbose_name='事项')),
                ('types', models.CharField(blank=True, default='按工厂', max_length=255, null=True, verbose_name='关联类型')),
                ('remind_date', models.CharField(blank=True, max_length=255, null=True, verbose_name='提醒日期')),
                ('date_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='时间类型')),
                ('preset1', models.TextField(blank=True, null=True, verbose_name='预留字段1')),
                ('preset2', models.TextField(blank=True, null=True, verbose_name='预留字段2')),
                ('preset3', models.TextField(blank=True, null=True, verbose_name='预留字段3')),
                ('preset4', models.TextField(blank=True, null=True, verbose_name='预留字段4')),
                ('preset5', models.TextField(blank=True, null=True, verbose_name='预留字段5')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '工厂进度',
                'verbose_name_plural': '工厂进度',
                'db_table': 'factory_process',
                'ordering': ['things'],
            },
        ),
        migrations.CreateModel(
            name='TextureReminds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texture_cate', models.CharField(blank=True, max_length=255, null=True, verbose_name='材质分类')),
                ('things', models.TextField(blank=True, null=True, verbose_name='事项')),
                ('remind_date', models.CharField(blank=True, max_length=255, null=True, verbose_name='提醒日期')),
                ('date_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='时间类型')),
                ('preset1', models.TextField(blank=True, null=True, verbose_name='预留字段1')),
                ('preset2', models.TextField(blank=True, null=True, verbose_name='预留字段2')),
                ('preset3', models.TextField(blank=True, null=True, verbose_name='预留字段3')),
                ('preset4', models.TextField(blank=True, null=True, verbose_name='预留字段4')),
                ('preset5', models.TextField(blank=True, null=True, verbose_name='预留字段5')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '材质进度',
                'verbose_name_plural': '材质进度',
                'db_table': 'texture_reminds',
                'ordering': ['remind_date'],
            },
        ),
    ]
