# Generated by Django 2.1.7 on 2020-02-16 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POM', '0002_factoryability_factoryprocess_texturereminds'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factoryability',
            options={'ordering': ['factory'], 'verbose_name': '工厂产能信息', 'verbose_name_plural': '工厂产能信息'},
        ),
        migrations.AlterModelOptions(
            name='factoryprocess',
            options={'ordering': ['things'], 'verbose_name': '工厂进度信息', 'verbose_name_plural': '工厂进度信息'},
        ),
        migrations.AlterModelOptions(
            name='texturereminds',
            options={'ordering': ['remind_date'], 'verbose_name': '材质进度信息', 'verbose_name_plural': '材质进度信息'},
        ),
        migrations.AddField(
            model_name='factoryability',
            name='formula',
            field=models.TextField(blank=True, null=True, verbose_name='产能计算公式'),
        ),
        migrations.AddField(
            model_name='factoryability',
            name='formula_expire_date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='公式失效日期'),
        ),
        migrations.AlterField(
            model_name='factoryability',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ability_factory', to='Basic_info.Factory', verbose_name='工厂'),
        ),
    ]
