# Generated by Django 2.1.7 on 2020-02-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POM', '0004_factoryability_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='remind',
            name='manage_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='管理事件的id'),
        ),
    ]
