# Generated by Django 2.1.7 on 2020-02-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POM', '0005_remind_manage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='remind',
            name='delay_date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='延期日期'),
        ),
        migrations.AlterField(
            model_name='remind',
            name='manage_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='延期事件的id'),
        ),
    ]
