# Generated by Django 2.1.7 on 2020-02-04 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='customer_item',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='客人货号'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_factory', to='Basic_info.Factory', verbose_name='生产工厂'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='item_no',
            field=models.CharField(max_length=255, verbose_name='Item NO'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='fmr',
            name='item_no',
            field=models.CharField(max_length=255, verbose_name='Item NO'),
        ),
        migrations.AlterField(
            model_name='fmr',
            name='oa_sure_date',
            field=models.CharField(max_length=255, verbose_name='OA确认日期'),
        ),
        migrations.AlterField(
            model_name='fmr',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='material_sign',
            name='amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='产品数量'),
        ),
        migrations.AlterField(
            model_name='material_sign',
            name='customer_item',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='客人NO'),
        ),
        migrations.AlterField(
            model_name='material_sign',
            name='customer_pono',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='客人PO#'),
        ),
        migrations.AlterField(
            model_name='material_sign',
            name='item_no',
            field=models.CharField(max_length=255, verbose_name='Item NO'),
        ),
        migrations.AlterField(
            model_name='material_sign',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='产品名称'),
        ),
        migrations.AlterField(
            model_name='material_sign',
            name='omr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='承办人员'),
        ),
        migrations.AlterField(
            model_name='material_sign',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='material_sign',
            name='unit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='计量单位'),
        ),
        migrations.AlterField(
            model_name='material_sign_detail',
            name='item_no',
            field=models.CharField(max_length=255, verbose_name='Item NO'),
        ),
        migrations.AlterField(
            model_name='material_sign_detail',
            name='remark',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='omr_po_detail',
            name='amount',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='omr_po_detail',
            name='cus_receive_date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='客人收货日期'),
        ),
        migrations.AlterField(
            model_name='omr_po_detail',
            name='customer_pono',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='客人PO#'),
        ),
        migrations.AlterField(
            model_name='omr_po_detail',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='产品描述'),
        ),
        migrations.AlterField(
            model_name='omr_po_detail',
            name='fac_send_date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='工厂交货期'),
        ),
        migrations.AlterField(
            model_name='omr_po_detail',
            name='factory',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='下单工厂'),
        ),
        migrations.AlterField(
            model_name='omr_po_detail',
            name='item_no',
            field=models.CharField(max_length=255, verbose_name='Item NO'),
        ),
        migrations.AlterField(
            model_name='omr_po_detail',
            name='port',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='出货港口'),
        ),
        migrations.AlterField(
            model_name='omr_po_detail',
            name='process',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='进度'),
        ),
        migrations.AlterField(
            model_name='omr_po_detail',
            name='receive_date',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PO接单日期'),
        ),
        migrations.AlterField(
            model_name='omr_po_detail',
            name='texture',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='材质'),
        ),
        migrations.AlterField(
            model_name='omr_po_detail',
            name='unit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='数量单位'),
        ),
        migrations.AlterField(
            model_name='po',
            name='delivery_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_delivery_condition', to='Basic_info.Delivery', verbose_name='客人交货条件'),
        ),
        migrations.AlterField(
            model_name='po',
            name='omr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_omr', to='Basic_info.Staff', verbose_name='承办员'),
        ),
        migrations.AlterField(
            model_name='po',
            name='ship_style',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='备用'),
        ),
        migrations.AlterField(
            model_name='po_detail',
            name='customer_item',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='客人Item NO'),
        ),
        migrations.AlterField(
            model_name='po_detail',
            name='fac_delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_detail_fac_delivery', to='Basic_info.Delivery', verbose_name='工厂交货条件'),
        ),
        migrations.AlterField(
            model_name='po_detail',
            name='fac_delivery_port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='po_detail_fac_port', to='Basic_info.Export_port', verbose_name='工厂出货港口'),
        ),
        migrations.AlterField(
            model_name='po_detail',
            name='item_no',
            field=models.CharField(max_length=255, verbose_name='我司Item NO'),
        ),
        migrations.AlterField(
            model_name='po_detail',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='product_send',
            name='customer_item',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='客人货号'),
        ),
        migrations.AlterField(
            model_name='product_send',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='产品名称'),
        ),
        migrations.AlterField(
            model_name='product_send',
            name='fac_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='工厂货号'),
        ),
        migrations.AlterField(
            model_name='product_send',
            name='fmr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_send_fmr', to='Basic_info.Staff', verbose_name='FMR'),
        ),
        migrations.AlterField(
            model_name='product_send',
            name='item_no',
            field=models.CharField(max_length=255, verbose_name='Item NO'),
        ),
        migrations.AlterField(
            model_name='product_send',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='备注'),
        ),
    ]
