# Generated by Django 2.1.7 on 2020-02-19 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('POM', '0003_auto_20200216_1838'),
        ('Order', '0004_auto_20200219_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='po_detail',
            name='fac_ability',
        ),
        migrations.AddField(
            model_name='po_detail',
            name='fty_ability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fac_ability', to='POM.FactoryAbility', verbose_name='工厂产能信息'),
        ),
    ]
