# Generated by Django 2.1.7 on 2020-02-19 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_auto_20200219_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='po_detail',
            name='fty_ability',
        ),
    ]
